version: '3.8'

services:
  mcp-messaging-server:
    build: .
    container_name: mcp-messaging-server
    ports:
      - "8123:8123"
    environment:
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8123
      - LOG_LEVEL=INFO
      - QUEUE_BACKEND=memory
    volumes:
      # Mount configuration files if needed
      - ./examples:/app/examples:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Optional: Redis backend for future use
  # redis:
  #   image: redis:7-alpine
  #   container_name: mcp-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - mcp-network

networks:
  mcp-network:
    driver: bridge

# volumes:
#   redis_data: 